# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/events.proto\"\xff\x01\n\x0cSyscallEvent\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12\x0c\n\x04\x63omm\x18\x02 \x01(\t\x12&\n\nevent_type\x18\x03 \x01(\x0e\x32\x12.SyscallEvent.Type\x12\x14\n\x0ctimestamp_ns\x18\x04 \x01(\x04\x12-\n\x08metadata\x18\x05 \x03(\x0b\x32\x1b.SyscallEvent.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"6\n\x04Type\x12\n\n\x06\x45XECVE\x10\x00\x12\n\n\x06OPENAT\x10\x01\x12\x0b\n\x07\x43ONNECT\x10\x02\x12\t\n\x05WRITE\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SYSCALLEVENT_METADATAENTRY._options = None
  _SYSCALLEVENT_METADATAENTRY._serialized_options = b'8\001'
  _SYSCALLEVENT._serialized_start=23
  _SYSCALLEVENT._serialized_end=278
  _SYSCALLEVENT_METADATAENTRY._serialized_start=175
  _SYSCALLEVENT_METADATAENTRY._serialized_end=222
  _SYSCALLEVENT_TYPE._serialized_start=224
  _SYSCALLEVENT_TYPE._serialized_end=278
# @@protoc_insertion_point(module_scope)
